
var exampleData = [
  {"Title":"Gladiator","Year":"2000","Rated":"R","Released":"05 May 2000","Runtime":"155 min","Genre":"Action, Adventure, Drama","Director":"Ridley Scott","Writer":"David Franzoni (story), David Franzoni (screenplay), John Logan (screenplay), William Nicholson (screenplay)","Actors":"Russell Crowe, Joaquin Phoenix, Connie Nielsen, Oliver Reed","Plot":"When a Roman general is betrayed and his family murdered by an emperor's corrupt son, he comes to Rome as a gladiator to seek revenge.","Language":"English","Country":"USA, UK","Awards":"Won 5 Oscars. Another 53 wins & 101 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMTgwMzQzNTQ1Ml5BMl5BanBnXkFtZTgwMDY2NTYxMTE@._V1_SX300.jpg","Metascore":"64","imdbRating":"8.5","imdbVotes":"1,000,080","imdbID":"tt0172495","Type":"movie","Response":"True"},
  {"Title":"Terminator","Year":"2001","Rated":"N/A","Released":"01 Apr 2001","Runtime":"N/A","Genre":"Short, Action","Director":"Ryan McDonald","Writer":"Ryan McDonald","Actors":"Joshua Miller","Plot":"N/A","Language":"English","Country":"USA","Awards":"N/A","Poster":"N/A","Metascore":"N/A","imdbRating":"4.8","imdbVotes":"16","imdbID":"tt1994570","Type":"movie","Response":"True"},
  {"Title":"Interstellar","Year":"2014","Rated":"PG-13","Released":"07 Nov 2014","Runtime":"169 min","Genre":"Adventure, Drama, Sci-Fi","Director":"Christopher Nolan","Writer":"Jonathan Nolan, Christopher Nolan","Actors":"Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow","Plot":"A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.","Language":"English","Country":"USA, UK","Awards":"Won 1 Oscar. Another 39 wins & 134 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BMjIxNTU4MzY4MF5BMl5BanBnXkFtZTgwMzM4ODI3MjE@._V1_SX300.jpg","Metascore":"74","imdbRating":"8.6","imdbVotes":"961,788","imdbID":"tt0816692","Type":"movie","Response":"True"},
  {"Title":"Gravity","Year":"2013","Rated":"PG-13","Released":"04 Oct 2013","Runtime":"91 min","Genre":"Adventure, Drama, Sci-Fi","Director":"Alfonso Cuarón","Writer":"Alfonso Cuarón, Jonás Cuarón","Actors":"Sandra Bullock, George Clooney, Ed Harris, Orto Ignatiussen","Plot":"A medical engineer and an astronaut work together to survive after an accident leaves them adrift in space.","Language":"English, Greenlandic","Country":"UK, USA","Awards":"Won 7 Oscars. Another 215 wins & 169 nominations.","Poster":"https://images-na.ssl-images-amazon.com/images/M/MV5BNjE5MzYwMzYxMF5BMl5BanBnXkFtZTcwOTk4MTk0OQ@@._V1_SX300.jpg","Metascore":"96","imdbRating":"7.8","imdbVotes":"590,779","imdbID":"tt1454468","Type":"movie","Response":"True"}
]


window.exampleData = exampleData;
